ARG ARCH=x86_64
FROM harbor.mellanox.com/swx-infra/$ARCH/fedora32:clang

ENV DEBIAN_FRONTEND=noninteractive

RUN yum install -y sudo \
    psmisc

ENV MODULEPATH /hpc/local/etc/modulefiles
SHELL ["/bin/bash"]

USER root
ENTRYPOINT [ "/bin/bash", "--login", "--rcfile", "/etc/bashrc", "-c" ]
