ARG ARCH=x86_64
ARG HARBOR_URL=nbu-harbor.gtm.nvidia.com
ARG OS_VERSION=23.01

FROM ${HARBOR_URL}/swx-infra/media/${ARCH}/base/ctyunos:${OS_VERSION}
ARG WEBREPO_URL=webrepo.gtm.nvidia.com
ARG OS_VERSION
ARG ARCH
ARG _UID=6213
ARG _GID=101
ARG _LOGIN=swx-jenkins
ARG _HOME=/var/home/$_LOGIN

RUN sed -i "s!baseurl=.*everything.*!baseurl=http://${WEBREPO_URL}/Ctyunos/Mirrors/${OS_VERSION}/\$basearch/everything/!" /etc/yum.repos.d/ctyunos.repo && \
    sed -i "s!baseurl=.*update.*!baseurl=http://${WEBREPO_URL}/Ctyunos/Mirrors/${OS_VERSION}/\$basearch/update/!" /etc/yum.repos.d/ctyunos.repo && \
    sed -i "s!baseurl=.*extras.*!baseurl=http://${WEBREPO_URL}/Ctyunos/Mirrors/${OS_VERSION}/\$basearch/extras/!" /etc/yum.repos.d/ctyunos.repo && \
    dnf clean all

RUN dnf --releasever=$OS_VERSION install -y \
    autoconf \
    automake \
    curl \
    environment-modules \
    ethtool \
    fuse-libs \
    gcc-c++ \
    git \
    json-c-devel \
    libmnl \
    libnl3-devel \
    libtool \
    libusbx \
    lsof \
    make \
    net-tools \
    numactl-libs \
    pciutils \
    rpm-build \
    sudo \
    tcl \
    tcsh \
    tk \
    util-linux \
    wget \
 && dnf clean all \
 && rm -rf /var/cache/dnf

RUN echo "${_LOGIN} ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers && \
    echo "root ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers && \
    mkdir -p ${_HOME} && \
    groupadd -f -g "$_GID" "$_LOGIN" && \
    useradd -u "$_UID" -g "$_GID" -s /bin/bash -m -d ${_HOME} "${_LOGIN}" && \
    chown -R ${_LOGIN} ${_HOME}

# W/A for RHEL/CentOS 7+ to allow sudo (by commenting out "session required pam_limits.so")
RUN for FILE in sudo-i sudo system-auth; do sed -i 's/session.*required.*pam_limits.so/#&/' /etc/pam.d/$FILE; done

# Install DOCA
COPY .ci/scripts/doca_install.sh /tmp/doca_install.sh
RUN chmod +x /tmp/doca_install.sh && \
    /tmp/doca_install.sh && \
    rm -f /tmp/doca_install.sh /tmp/GPG-KEY-Mellanox.pub

ENV MODULEPATH /hpc/local/etc/modulefiles
SHELL ["/bin/bash"]

USER "$_LOGIN"
ENTRYPOINT [ "/bin/bash", "--login", "--rcfile", "/etc/bashrc", "-c" ]
