FROM harbor.mellanox.com/rivermax/dpcp/x86_64/rhel8.6/core:8.6
ARG _UID=6213
ARG _GID=101
ARG _LOGIN=swx-jenkins
ARG _HOME=/var/home/$_LOGIN

RUN dnf module disable -y perl* && \
    dnf remove perl-IO-Socket-SSL && \
    dnf remove perl-libwww-perl && \
    dnf install -y perl-IO-Socket-SSL && \
    dnf install -y perl-libwww-perl

RUN  sed -i 's/enabled=1/enabled=0/g' /etc/yum/pluginconf.d/subscription-manager.conf

RUN sed -i 's/mirrorlist/#mirrorlist/;s!#baseurl=http://mirror.centos.org!baseurl=http://vault.centos.org!' /etc/yum.repos.d/* && \
    echo "[mlnx-opt]" > /etc/yum.repos.d/mlnx-opt.repo && \
    echo "name=RHEL 8.6 mirror" >> /etc/yum.repos.d/mlnx-opt.repo && \
    echo "baseurl=http://webrepo.mtr.labs.mlnx/RH/8.6/x86_64/BaseOS/" >> /etc/yum.repos.d/mlnx-opt.repo && \
    echo "enabled=1" >> /etc/yum.repos.d/mlnx-opt.repo && \
    echo "gpgcheck=0" >> /etc/yum.repos.d/mlnx-opt.repo && \
    yum makecache

RUN yum install --allowerasing -y \
    atk \
    autoconf \
    automake \
    cairo \
    curl \
    java-11-openjdk \
    gcc-gfortran \
    gcc-c++ \
    git \
    net-tools \
    gtk2 \
    kernel-modules-extra \
    libmnl \
    libnl3 \
    libnl3-devel \
    libtool \
    libusbx \
    fuse-libs \
    lsof \
    make \
    numactl-libs \
    pciutils \
    rpm-build \
    sudo \
    tcl \
    tk \
    wget \
    environment-modules \
    pkgconfig \
    python38 \
    python3-pip \
    graphviz

# MOFED
ARG MOFED_OS=rhel8.6
ARG MOFED_VERSION=23.07-0.5.1.2
ENV MOFED_DIR MLNX_OFED_LINUX-${MOFED_VERSION}-${MOFED_OS}-x86_64
ENV MOFED_SITE_PLACE MLNX_OFED-${MOFED_VERSION}
ENV MOFED_IMAGE ${MOFED_DIR}.tgz

RUN wget --no-verbose http://content.mellanox.com/ofed/${MOFED_SITE_PLACE}/${MOFED_IMAGE} && \
    tar -xzf ${MOFED_IMAGE} && \
    ${MOFED_DIR}/mlnxofedinstall --all -q \
	--force \
	--upstream-libs \
	--vma \
	--user-space-only \
	--without-fw-update \
	--skip-unsupported-devices-check \
	--without-libxlio \
	--without-libxlio-utils \
	--without-libxlio-dev \
        --distro ${MOFED_OS} \
    && rm -rf ${MOFED_DIR} && rm -rf *.tgz


RUN echo "${_LOGIN} ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers && \
    echo "root ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers && \
    mkdir -p ${_HOME} && \
    groupadd -f -g "$_GID" "$_LOGIN" && \
    useradd -u "$_UID" -g "$_GID" -s /bin/bash -m -d ${_HOME} "${_LOGIN}" && \
    chown -R ${_LOGIN} ${_HOME}

# W/A for RHEL/CentOS 7 to allow sudo (by commenting out "session required pam_limits.so")
RUN for FILE in sudo-i sudo system-auth; do sed -i 's/session.*required.*pam_limits.so/#&/' /etc/pam.d/$FILE; done

ENV MODULEPATH /hpc/local/etc/modulefiles
SHELL ["/bin/bash"]

USER "$_LOGIN"
ENTRYPOINT [ "/bin/bash", "--login", "--rcfile", "/etc/bashrc", "-c" ]

