FROM harbor.mellanox.com/rivermax/dpcp/x86_64/rhel9.2/core:9.2
ARG _UID=6213
ARG _GID=101
ARG _LOGIN=swx-jenkins
ARG _HOME=/var/home/$_LOGIN

RUN dnf remove subscription-manager -y && \
    dnf remove perl-IO-Socket-SSL && \
    dnf remove perl-libwww-perl && \
    dnf install -y perl-IO-Socket-SSL && \
    dnf install -y perl-libwww-perl

RUN sed -i 's/mirrorlist/#mirrorlist/;s!#baseurl=http://mirror.centos.org!baseurl=http://vault.centos.org!' /etc/yum.repos.d/* && \
    echo "[mlnx-opt]" > /etc/yum.repos.d/mlnx-opt.repo && \
    echo "name=RHEL 9.2 mirror" >> /etc/yum.repos.d/mlnx-opt.repo && \
    echo "baseurl=http://webrepo.mtr.labs.mlnx/RH/9.2/x86_64/BaseOS" >> /etc/yum.repos.d/mlnx-opt.repo && \
    echo "enabled=1" >> /etc/yum.repos.d/mlnx-opt.repo && \
    echo "gpgcheck=0" >> /etc/yum.repos.d/mlnx-opt.repo && \
    echo "[mlnx-Ext]" >> /etc/yum.repos.d/mlnx-opt.repo && \
    echo "name=RHEL 9.2 Ext mirror" >> /etc/yum.repos.d/mlnx-opt.repo && \
    echo "baseurl=http://webrepo.mtr.labs.mlnx/RH/9.2/x86_64/AppStream" >> /etc/yum.repos.d/mlnx-opt.repo && \
    echo "enabled=1" >> /etc/yum.repos.d/mlnx-opt.repo && \
    echo "gpgcheck=0" >> /etc/yum.repos.d/mlnx-opt.repo && \
    yum makecache

RUN yum install --allowerasing -y \
    atk \
    autoconf \
    automake \
    cairo \
    curl \
    java-11-openjdk \
    gcc-gfortran \
    gcc-c++ \
    git \
    net-tools \
    gtk2 \
    kernel-modules-extra \
    libmnl \
    libnl3 \
    libnl3-devel \
    libtool \
    libusbx \
    fuse-libs \
    lsof \
    make \
    numactl-libs \
    pciutils \
    rpm-build \
    sudo \
    tcl \
    tcsh \
    tk \
    wget \
    environment-modules \
    python3-pip \
    perl-sigtrap \
    ethtool \
    https://mirror.stream.centos.org/9-stream/CRB/x86_64/os/Packages/avahi-devel-0.8-12.el9.x86_64.rpm \
    https://mirror.stream.centos.org/9-stream/CRB/x86_64/os/Packages/avahi-compat-libdns_sd-0.8-12.el9.x86_64.rpm \
    https://mirror.stream.centos.org/9-stream/CRB/x86_64/os/Packages/avahi-compat-libdns_sd-devel-0.8-12.el9.x86_64.rpm \
    dbus-devel \
    graphviz \    
    https://mirror.stream.centos.org/9-stream/CRB/x86_64/os/Packages/doxygen-1.9.1-11.el9.x86_64.rpm 

RUN echo "${_LOGIN} ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers && \
    echo "root ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers && \
    mkdir -p ${_HOME} && \
    groupadd -f -g "$_GID" "$_LOGIN" && \
    useradd -u "$_UID" -g "$_GID" -s /bin/bash -m -d ${_HOME} "${_LOGIN}" && \
    chown -R ${_LOGIN} ${_HOME}

# W/A for RHEL/CentOS 7 to allow sudo (by commenting out "session required pam_limits.so")
RUN for FILE in sudo-i sudo system-auth; do sed -i 's/session.*required.*pam_limits.so/#&/' /etc/pam.d/$FILE; done

ENV MODULEPATH /hpc/local/etc/modulefiles
SHELL ["/bin/bash"]

USER "$_LOGIN"
ENTRYPOINT [ "/bin/bash", "--login", "--rcfile", "/etc/bashrc", "-c" ]

