ARG ARCH=x86_64
ARG HARBOR_URL=nbu-harbor.gtm.nvidia.com
FROM ${HARBOR_URL}/swx-infra/media/${ARCH}/base/rhel:9.6 AS build
ARG WEBREPO_URL=webrepo.gtm.nvidia.com
ARG ARCH
ARG _UID=6213
ARG _GID=101
ARG _LOGIN=swx-jenkins
ARG _HOME=/var/home/$_LOGIN

RUN dnf remove subscription-manager -y && \
    dnf remove perl-IO-Socket-SSL && \
    dnf remove perl-libwww-perl && \
    dnf install -y perl-IO-Socket-SSL && \
    dnf install -y perl-libwww-perl && \
    rm -rf /var/cache/dnf

RUN sed -i "s#http://webrepo#http://${WEBREPO_URL}#" /etc/yum.repos.d/* && \
    sed -i 's/mirrorlist/#mirrorlist/;s!#baseurl=http://mirror.centos.org!baseurl=http://vault.centos.org!' /etc/yum.repos.d/* && \
    ## Disable UBI repo that comes from source container
    rm -f /etc/yum.repos.d/ubi.repo && \
    ## Add webrepo RH repos
    echo "[mlnx-opt]" > /etc/yum.repos.d/mlnx-opt.repo && \
    echo "name=RHEL 9.6 mirror" >> /etc/yum.repos.d/mlnx-opt.repo && \
    echo "baseurl=http://${WEBREPO_URL}/RH/9.6/${ARCH}/BaseOS" >> /etc/yum.repos.d/mlnx-opt.repo && \
    echo "enabled=1" >> /etc/yum.repos.d/mlnx-opt.repo && \
    echo "gpgcheck=0" >> /etc/yum.repos.d/mlnx-opt.repo && \
    echo "[mlnx-Ext]" >> /etc/yum.repos.d/mlnx-opt.repo && \
    echo "name=RHEL 9.6 Ext mirror" >> /etc/yum.repos.d/mlnx-opt.repo && \
    echo "baseurl=http://${WEBREPO_URL}/RH/9.6/${ARCH}/AppStream" >> /etc/yum.repos.d/mlnx-opt.repo && \
    echo "enabled=1" >> /etc/yum.repos.d/mlnx-opt.repo && \
    echo "gpgcheck=0" >> /etc/yum.repos.d/mlnx-opt.repo && \
    echo "[mlnx-CRB]" >> /etc/yum.repos.d/mlnx-opt.repo && \
    echo "name=RHEL 9.6 Ext mirror" >> /etc/yum.repos.d/mlnx-opt.repo && \
    echo "baseurl=http://${WEBREPO_URL}/RH/rh-mirrors/9.6/CRB/${ARCH}/" >> /etc/yum.repos.d/mlnx-opt.repo && \
    echo "enabled=1" >> /etc/yum.repos.d/mlnx-opt.repo && \
    echo "gpgcheck=0" >> /etc/yum.repos.d/mlnx-opt.repo && \
    yum makecache

RUN yum install --allowerasing -y \
    atk \
    autoconf \
    automake \
    cairo \
    curl \
    java-11-openjdk \
    gcc-gfortran \
    gcc-c++ \
    git \
    net-tools \
    gtk2 \
    kernel-modules-extra \
    libmnl \
    libnl3-devel \
    libtool \
    libusbx \
    fuse-libs \
    lsof \
    make \
    numactl-libs \
    pciutils \
    rpm-build \
    sudo \
    tcl \
    tcsh \
    tk \
    wget \
    environment-modules \
    python3-pip \
    perl-sigtrap \
    ethtool \
    avahi-devel \
    avahi-compat-libdns_sd \
    avahi-compat-libdns_sd-devel \
    dbus-devel \
    graphviz \
    doxygen

RUN echo "${_LOGIN} ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers && \
    echo "root ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers && \
    mkdir -p ${_HOME} && \
    groupadd -f -g "$_GID" "$_LOGIN" && \
    useradd -u "$_UID" -g "$_GID" -s /bin/bash -m -d ${_HOME} "${_LOGIN}" && \
    chown -R ${_LOGIN} ${_HOME}

# W/A for RHEL/CentOS 7+ to allow sudo (by commenting out "session required pam_limits.so")
RUN for FILE in sudo-i sudo system-auth; do sed -i 's/session.*required.*pam_limits.so/#&/' /etc/pam.d/$FILE; done

# Install DOCA
COPY .ci/scripts/doca_install.sh /tmp/doca_install.sh
RUN chmod +x /tmp/doca_install.sh && \
    /tmp/doca_install.sh && \
    rm -f /tmp/doca_install.sh /tmp/GPG-KEY-Mellanox.pub

ENV MODULEPATH /hpc/local/etc/modulefiles
SHELL ["/bin/bash"]

USER "$_LOGIN"
ENTRYPOINT [ "/bin/bash", "--login", "--rcfile", "/etc/bashrc", "-c" ]
